language: ruby
rvm:
  - 1.9.3
  - 2.0.0
env:
  - DB=postgresql
before_script:
  - cp config/databse.yml.ci config/database.yml
  - psql -c 'create database ticketee_test;' -U postgres
  - rake db:create:all
  - rake db:migrate
script:
  - RAILS_ENV=test bundle exec rspec spec/
  - rake spec
